name: Deploy

on:
  push:
    branches:
      - main # Branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest # Machine you want to deploy on

    steps:
    - name: Checkout code # will copy code on unbuntu machine
      uses: actions/checkout@v2 

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run:
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ssh -t -i keyfile ubuntu@ec2-13-127-199-188.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
